<a href="https://colab.research.google.com/github/kalvin-osoro/AI-ML-Group-Task/blob/main/Ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import numpy as np
from numpy import array
import pandas as pd
from sklearn.preprocessing import Normalizer
from numpy.random import uniform,normal

data_dict={'Day 1':[30,40,50,20,15,60],
           'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],
           'Target':[20,15,60,70,50,40]}

data=pd.DataFrame(data_dict)

x=data.drop('Target',axis=1)
y=data['Target']

x_trans=Normalizer(norm='max').fit_transform(x)

X=x_trans

np.reshape(array(y),(-1,1))

y=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))




# scale units
X = X/np.amax(X, axis=0) #maximum of X array
y = y/100 # maximum test score is 100

class NeuralNetwork(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
      
        
        # weights
        self.W1=uniform(-1,1,(3,2))#shape of 3 by 2
        self.W2=uniform(-1,1,(2,6))#shape of 3 by 1
        
    def feedForward(self, X):
        #forward propogation through the network
        self.z = np.dot(X, self.W1) #dot product of X (input) and first set of weights (3x2)
        self.z2 = self.sigmoid(self.z) #activation function
        self.z3 = np.dot(self.z2, self.W2) #dot product of hidden layer (z2) and second set of weights (3x1)
        output = self.sigmoid(self.z3)
        return output
        
    def sigmoid(self, s, deriv=False):
        if (deriv == True):
            return s * (1 - s)
        return 1/(1 + np.exp(-s))
    
    def backward(self, X, y, output):
        #backward propogate through the network
        self.output_error = y - output # error in output
        delta= self.output_delta = self.output_error * self.sigmoid(output, deriv=True)


        
        self.z2_error = self.output_delta.dot(self.W2.T) #z2 error: how much our hidden layer weights contribute to output error
        self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv=True) #applying derivative of sigmoid to z2 error
        
        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input -> hidden) weights
        self.W2 += self.z2.T.dot(self.output_delta) # adjusting second set (hidden -> output) weights

        print("weight 1: "+ str(self.W1))

        print("weight 2: "+ str(self.W2))
        
    def train(self, X, y):
        output = self.feedForward(X)
        self.backward(X, y, output)
        
NN = NeuralNetwork()

for i in range(100): #trains the NN 1000 times
    if (i % 100 == 0):
        print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
    NN.train(X, y)
        
print("Input: " + str(X))
print("Actual Output: " + str(y))
print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
print("\n")
print("Predicted Output: " + str(NN.feedForward(X)))

# print("weight 1: "+ str(W1))


Loss: 0.2324051476581558
weight 1: [[ 0.04065998  0.31755505]
 [-0.70116905 -0.76322672]
 [ 0.41595268  0.71691159]]
weight 2: [[-0.334328   -0.00775963  0.32402301 -0.20442015 -0.082792   -1.22930215]
 [-0.60132969 -0.45330025 -0.84349676 -0.42165615 -1.25839457  0.12595191]]
weight 1: [[ 0.16502148  0.60764138]
 [-0.5595975  -0.43170937]
 [ 0.55756866  1.04336392]]
weight 2: [[-0.57876237 -0.30140744  0.0472476  -0.47758775 -0.27405108 -1.46883327]
 [-0.89214826 -0.80256582 -1.17269194 -0.74659729 -1.48600469 -0.15909564]]
weight 1: [[ 0.33943367  0.85965144]
 [-0.36120896 -0.14605743]
 [ 0.75038587  1.31293827]]
weight 2: [[-0.75821246 -0.52759652 -0.15777687 -0.68594651 -0.40296854 -1.65490488]
 [-1.12967322 -1.10169272 -1.44377153 -1.02224438 -1.65670409 -0.40563056]]
weight 1: [[ 0.46858241  1.00204059]
 [-0.21628255  0.01106157]
 [ 0.88834012  1.45931836]]
weight 2: [[-0.8773573  -0.67752841 -0.29520047 -0.82395328 -0.48975781 -1.77583351]
 [-1.28304791 -1.29459781 -1.62052773 -