<a href="https://colab.research.google.com/github/kalvin-osoro/AI-ML-Group-Task/blob/main/Ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
from numpy import array
import pandas as pd
from sklearn.preprocessing import Normalizer
from numpy.random import uniform,normal

data_dict={'Day 1':[30,40,50,20,15,60],
           'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],
           'Target':[20,15,60,70,50,40]}

data=pd.DataFrame(data_dict)

x=data.drop('Target',axis=1)
y=data['Target']

x_trans=Normalizer(norm='max').fit_transform(x)

X=x_trans

np.reshape(array(y),(-1,1))

y=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))


class NeuralNetwork(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
      
        
        # weights
        self.W1=uniform(-1,1,(3,2))
        self.W2=uniform(-1,1,(2,6))
        
    def feedForward(self, X):
        #forward propogation through the network
        self.z = np.dot(X, self.W1) #dot product of X (input) and first set of weights (3x2)
        self.z2 = self.sigmoid(self.z) #activation function
        self.z3 = np.dot(self.z2, self.W2) #dot product of hidden layer (z2) and second set of weights (3x1)
        output = self.sigmoid(self.z3)
        return output
        
    def sigmoid(self, s, deriv=False):
        if (deriv == True):
            return s * (1 - s)
        return 1/(1 + np.exp(-s))
    
    def backward(self, X, y, output):
        #backward propogate through the network
        self.output_error = y - output # error in output
        delta= self.output_delta = self.output_error * self.sigmoid(output, deriv=True)
       
        self.z2_error = delta.dot(self.W2.T) #z2 error: how much our hidden layer weights contribute to output error
        self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv=True) #applying derivative of sigmoid to z2 error
        
        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input -> hidden) weights
        self.W2 += self.z2.T.dot(self.output_delta) # adjusting second set (hidden -> output) weights

       
        print("weight 1: "+ str(self.W1))
        print("weight 2: "+ str(self.W2))
       
    def train(self, X, y):
        output = self.feedForward(X)
        self.backward(X, y, output)
        
NN = NeuralNetwork()

for i in range(100): #trains the NN 1000 times
    if (i % 100 == 0):
        print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
    NN.train(X, y)
    X.T
    y.T

print("\n")       
print("Actual Output: " + str(y))
print("\n") 
print("Predicted Output: " + str(NN.feedForward(X[0])))
print("\n")
print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))


# print("weight 1: "+ str(W1))


Loss: 0.07732864744485579
weight 1: [[-0.57146204 -0.80168364]
 [ 0.74232507 -0.28523347]
 [ 0.51887921 -0.67889521]]
weight 2: [[-0.25056023 -1.07198562  0.63274676  0.32824677  0.19707529  0.69991059]
 [ 0.79811412  0.43939931 -0.51840387  1.09499986  0.76269508  0.40663162]]
weight 1: [[-0.46029165 -0.78452195]
 [ 0.85739565 -0.26517242]
 [ 0.63475126 -0.65908907]]
weight 2: [[-0.45874482 -1.19674154  0.89790725  0.67540571  0.32618822  0.64640955]
 [ 0.72158442  0.39250119 -0.42064694  1.22166883  0.8097625   0.38763458]]
weight 1: [[-0.33377086 -0.75871309]
 [ 0.98340129 -0.23636209]
 [ 0.76180618 -0.63029969]]
weight 2: [[-0.63960998 -1.29571552  1.11770302  0.95997248  0.43550484  0.58913548]
 [ 0.65789057  0.35667806 -0.34293489  1.32099566  0.84785108  0.36821943]]
weight 1: [[-0.22255628 -0.73169324]
 [ 1.08826594 -0.20701091]
 [ 0.86824554 -0.60089728]]
weight 2: [[-0.78660507 -1.36980425  1.29017108  1.18250649  0.5218996   0.52979415]
 [ 0.60729846  0.33034521 -0.2833407  