<a href="https://colab.research.google.com/github/kalvin-osoro/AI-ML-Group-Task/blob/main/Ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np
from numpy import array
import pandas as pd
from sklearn.preprocessing import Normalizer
from numpy.random import uniform,normal

data_dict={'Day 1':[30,40,50,20,15,60],
           'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],
           'Target':[20,15,60,70,50,40]}

data=pd.DataFrame(data_dict)

x=data.drop('Target',axis=1)
y=data['Target']

x_trans=Normalizer(norm='max').fit_transform(x)

X=x_trans

np.reshape(array(y),(-1,1))

y=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))


# X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
# y = np.array(([92], [86], [89]), dtype=float)

# scale units
X = X/np.amax(X, axis=0) #maximum of X array
y = y/100 # maximum test score is 100

class NeuralNetwork(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        #weights
        # self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        # self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer
        

        self.W1=uniform(-1,1,(3,2))#shape of 3 by 2
        self.W2=uniform(-1,1,(2,6))#shape of 3 by 1
        
    def feedForward(self, X):
        #forward propogation through the network
        self.z = np.dot(X, self.W1) #dot product of X (input) and first set of weights (3x2)
        self.z2 = self.sigmoid(self.z) #activation function
        self.z3 = np.dot(self.z2, self.W2) #dot product of hidden layer (z2) and second set of weights (3x1)
        output = self.sigmoid(self.z3)
        return output
        
    def sigmoid(self, s, deriv=False):
        if (deriv == True):
            return s * (1 - s)
        return 1/(1 + np.exp(-s))
    
    def backward(self, X, y, output):
        #backward propogate through the network
        self.output_error = y - output # error in output
        delta= self.output_delta = self.output_error * self.sigmoid(output, deriv=True)


        
        self.z2_error = self.output_delta.dot(self.W2.T) #z2 error: how much our hidden layer weights contribute to output error
        self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv=True) #applying derivative of sigmoid to z2 error
        
        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input -> hidden) weights
        self.W2 += self.z2.T.dot(self.output_delta) # adjusting second set (hidden -> output) weights

        print("weight 1: "+ str(self.W1))

        print("weight 2: "+ str(self.W2))
        
    def train(self, X, y):
        output = self.feedForward(X)
        self.backward(X, y, output)
        
NN = NeuralNetwork()

for i in range(100): #trains the NN 1000 times
    if (i % 100 == 0):
        print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
    NN.train(X, y)
        
print("Input: " + str(X))
print("Actual Output: " + str(y))
print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
print("\n")
print("Predicted Output: " + str(NN.feedForward(X)))

# print("weight 1: "+ str(W1))


Loss: 0.23421705200900483
weight 1: [[ 0.88415218 -0.03408872]
 [ 0.11437872  0.15164578]
 [-0.21788158 -0.15335429]]
weight 2: [[ 0.06066857 -0.65145021 -0.31611891 -0.99475129 -0.89456692  0.06565783]
 [-0.21180244 -0.83264112  0.51670004 -1.10562987 -0.91983944 -0.80762061]]
weight 1: [[ 1.01355187  0.13853795]
 [ 0.26814754  0.35055068]
 [-0.04944515  0.05755308]]
weight 2: [[-0.38258305 -0.89005958 -0.78304321 -1.1471914  -1.08200752 -0.29716772]
 [-0.56706146 -1.025036    0.14208517 -1.22915102 -1.07142992 -1.09849948]]
weight 1: [[1.17548988 0.32015525]
 [0.46064626 0.55715849]
 [0.16790716 0.28163435]]
weight 2: [[-0.71263028 -1.05261698 -1.15308201 -1.24971022 -1.20952294 -0.54796711]
 [-0.85356066 -1.16681302 -0.17956074 -1.31885545 -1.18287455 -1.31623484]]
weight 1: [[1.28111993 0.4435823 ]
 [0.58550307 0.69396634]
 [0.31710731 0.43602377]]
weight 2: [[-0.91471486 -1.15695913 -1.38510033 -1.31575785 -1.29206528 -0.70202626]
 [-1.03701588 -1.26173622 -0.39053734 -1.37903588 