<a href="https://colab.research.google.com/github/kalvin-osoro/AI-ML-Group-Task/blob/main/Ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np
from numpy import array
import pandas as pd
from sklearn.preprocessing import Normalizer
from numpy.random import uniform,normal
# X = (hours sleeping, hours studying), y = test score of the student

lrate = 1

data_dict={'Day 1':[30,40,50,20,15,60],
           'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],
           'Target':[20,15,60,70,50,40]}

data=pd.DataFrame(data_dict)

x=data.drop('Target',axis=1)
y=data['Target']

x_trans=Normalizer(norm='max').fit_transform(x)

X=x_trans

np.reshape(array(y),(-1,1))

y=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))


# X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
# y = np.array(([92], [86], [89]), dtype=float)

# scale units
X = X/np.amax(X, axis=0) #maximum of X array
y = y/100 # maximum test score is 100

class NeuralNetwork(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        #weights
        # self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        # self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer
        

        self.W1=uniform(-1,1,(3,2))#shape of 3 by 2
        self.W2=uniform(-1,1,(2,6))#shape of 3 by 1
        
    def feedForward(self, X):
        #forward propogation through the network
        self.z = np.dot(X, self.W1) #dot product of X (input) and first set of weights (3x2)
        self.z2 = self.sigmoid(self.z) #activation function
        self.z3 = np.dot(self.z2, self.W2) #dot product of hidden layer (z2) and second set of weights (3x1)
        output = self.sigmoid(self.z3)
        return output
        
    def sigmoid(self, s, deriv=False):
        if (deriv == True):
            return s * (1 - s)
        return 1/(1 + np.exp(-s))
    
    def backward(self, X, y, output):
        #backward propogate through the network
        self.output_error = y - output # error in output
        delta= self.output_delta = self.output_error * self.sigmoid(output, deriv=True)

        # nw= self.output_delta.transpose(6,2)
        np.reshape(array(delta),(-1,1))

        print("self.output_delta shape: " +str(delta.shape))

        
        self.z2_error = self.output_delta.dot(self.W2.T) #z2 error: how much our hidden layer weights contribute to output error
        self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv=True) #applying derivative of sigmoid to z2 error
        
        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input -> hidden) weights
        self.W2 += self.z2.T.dot(self.output_delta) # adjusting second set (hidden -> output) weights

        print("weight 1: "+ str(self.W1))

        print("weight 2: "+ str(self.W2))
        
    def train(self, X, y):
        output = self.feedForward(X)
        self.backward(X, y, output)
        
NN = NeuralNetwork()

for i in range(100): #trains the NN 1000 times
    if (i % 100 == 0):
        print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
    NN.train(X, y)
        
print("Input: " + str(X))
print("Actual Output: " + str(y))
print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
print("\n")
print("Predicted Output: " + str(NN.feedForward(X)))

# print("weight 1: "+ str(W1))


Loss: 0.35117660320104316
self.output_delta shape: (6, 6)
weight 1: [[ 0.67818319  0.70442663]
 [ 0.39134073 -0.17124763]
 [ 0.21198019 -0.30333352]]
weight 2: [[-0.19545044  0.03544709  0.2007619  -0.01899574 -1.04520045 -1.00135349]
 [-0.36555566 -0.55954834  0.43336411  0.05944999 -0.30226786 -0.56413929]]
self.output_delta shape: (6, 6)
weight 1: [[ 0.75465229  0.77111654]
 [ 0.48056244 -0.09282198]
 [ 0.31125255 -0.21948189]]
weight 2: [[-0.62126516 -0.41023222 -0.39265064 -0.54001217 -1.29073143 -1.21908988]
 [-0.68294866 -0.89154665 -0.01007241 -0.32969577 -0.48502045 -0.72585874]]
self.output_delta shape: (6, 6)
weight 1: [[ 0.91987935  0.92238528]
 [ 0.6714741   0.08520592]
 [ 0.52444423 -0.02789629]]
weight 2: [[-0.89830698 -0.69986866 -0.84571204 -0.89373564 -1.46099502 -1.37232531]
 [-0.8932884  -1.11123812 -0.35554307 -0.59893472 -0.6142675  -0.84195917]]
self.output_delta shape: (6, 6)
weight 1: [[1.03323403 1.04189983]
 [0.80047447 0.22747293]
 [0.67576509 0.1315956 ]]
w