<a href="https://colab.research.google.com/github/kalvin-osoro/AI-ML-Group-Task/blob/main/Ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
from numpy import array
import pandas as pd
from sklearn.preprocessing import Normalizer
from numpy.random import uniform,normal

data_dict={'Day 1':[30,40,50,20,15,60],
           'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],
           'Target':[20,15,60,70,50,40]}

data=pd.DataFrame(data_dict)

x=data.drop('Target',axis=1)
y=data['Target']

x_trans=Normalizer(norm='max').fit_transform(x)

X=x_trans

np.reshape(array(y),(-1,1))

y=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))




# scale units
# X = X/np.amax(X, axis=0) #maximum of X array
# y = y/100 # maximum test score is 100

class NeuralNetwork(object):
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
      
        
        # weights
        self.W1=uniform(-1,1,(3,2))#shape of 3 by 2
        self.W2=uniform(-1,1,(2,6))#shape of 3 by 1
        
    def feedForward(self, X):
        #forward propogation through the network
        self.z = np.dot(X, self.W1) #dot product of X (input) and first set of weights (3x2)
        self.z2 = self.sigmoid(self.z) #activation function
        self.z3 = np.dot(self.z2, self.W2) #dot product of hidden layer (z2) and second set of weights (3x1)
        output = self.sigmoid(self.z3)
        return output
        
    def sigmoid(self, s, deriv=False):
        if (deriv == True):
            return s * (1 - s)
        return 1/(1 + np.exp(-s))
    
    def backward(self, X, y, output):
        #backward propogate through the network
        self.output_error = y - output # error in output
        delta= self.output_delta = self.output_error * self.sigmoid(output, deriv=True)
       
        self.z2_error = delta.dot(self.W2.T) #z2 error: how much our hidden layer weights contribute to output error
        self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv=True) #applying derivative of sigmoid to z2 error
        
        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input -> hidden) weights
        self.W2 += self.z2.T.dot(self.output_delta) # adjusting second set (hidden -> output) weights

       
        print("weight 1: "+ str(self.W1))
        print("weight 2: "+ str(self.W2))
       
    def train(self, X, y):
        output = self.feedForward(X)
        self.backward(X, y, output)
        
NN = NeuralNetwork()

for i in range(100): #trains the NN 1000 times
    if (i % 100 == 0):
        print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
    NN.train(X, y)
    X.T
    y.T

print("\n")       
print("Actual Output: " + str(y))
print("\n") 
print("Predicted Output: " + str(NN.feedForward(X[0])))
print("\n")
print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))


# print("weight 1: "+ str(W1))


Loss: 0.09907353795877853
weight 1: [[-0.33630591 -0.10538292]
 [ 0.38793772 -0.79118725]
 [-0.96575795  0.48437737]]
weight 2: [[ 0.689779   -0.58604478  0.36644397 -0.46319986  0.83147387 -0.14545653]
 [-0.31415637 -0.97142123  0.03834317  0.75819728 -0.46277136 -0.71518721]]
weight 1: [[-0.34947753 -0.02304198]
 [ 0.37375443 -0.69767351]
 [-0.97561136  0.5750527 ]]
weight 2: [[ 0.56463533 -0.65032367  0.53198425 -0.22565255  0.92952297 -0.06558663]
 [-0.46774019 -1.04991406  0.24594386  1.05051445 -0.33650668 -0.61373495]]
weight 1: [[-0.31658078  0.10093232]
 [ 0.41143802 -0.55706166]
 [-0.93497785  0.71151658]]
weight 2: [[ 0.45820683 -0.70149975  0.67299145 -0.0308968   1.01706023  0.00824324]
 [-0.61391632 -1.12005103  0.44438248  1.3186076  -0.2099766  -0.50854804]]
weight 1: [[-0.25971525  0.23757323]
 [ 0.47610458 -0.40291137]
 [-0.86800332  0.85883208]]
weight 2: [[ 0.36556163 -0.7389935   0.79359068  0.12766553  1.09613116  0.08119385]
 [-0.75190119 -1.17599365  0.62902469 